### ISSUE TITLE
[feature] 공통 UI 제작

### ISSUE THREAD

**Issue by rhino-ty** [Wingle-SMWU/Wingle-Frontend#46]
## Description

Color, Text, Input, Drop Down, Button(Large, Small), Nodata 공통 UI 제작

1. 꼭 components/ui/개발할ui.tsx 이렇게 개발!
2. 브랜치 46-개발할ui 파서 개발!
3. 커밋할 때 `#46 -`  이렇게 만들기
4. components/ui.tsx는 나두기

## Todo

- [ ] Color Guide 제작
- [x] Button(Large, Small)
- [x] Text Guide 제작
- [x] Input 
- [x] Drop Down
- [x] Nodata
- [x] Loading
