### ISSUE TITLE
[feature] 타인 프로필 보기 페이지 추가 , 닉네임 수정  알람창 추가 

### ISSUE THREAD

**Issue by JudithHopps** [Wingle-SMWU/Wingle-Frontend#71]
## Description

타인 프로필 페이지 추가 
: 쿼리문으로 작성 

## Todo
- [x] 리턴 타입 추가
- [x] 타인 프로필 페이지 추가 
- [x] 닉네임 수정 시 기존 작성되어 있는지 확인
